# Generated by Django 6.0.3 on 2026-03-05 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID de sesión del usuario', max_length=100)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'conversaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('url_origen', models.URLField()),
                ('contenido_texto', models.TextField(blank=True)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'documentos_pdf',
            },
        ),
        migrations.CreateModel(
            name='ConocimientoUAEMEX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('facultad', 'Facultad'), ('carrera', 'Carrera'), ('reglamento', 'Reglamento'), ('contacto', 'Contacto'), ('general', 'Información General')], default='general', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conocimiento_uaemex',
                'indexes': [models.Index(fields=['titulo'], name='conocimient_titulo_82a070_idx'), models.Index(fields=['tipo'], name='conocimient_tipo_fb0e00_idx')],
            },
        ),
    ]
