# Generated by Django 5.1.6 on 2026-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_make_fuente_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conocimientouaemex",
            name="fuente",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
