# Generated by Django 5.1.6 on 2026-03-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_make_fuente_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentopdf",
            name="hash_contenido",
            field=models.CharField(
                blank=True,
                help_text="MD5 del contenido del PDF para detectar cambios",
                max_length=64,
            ),
        ),
    ]
