# Generated by Django 5.1.6 on 2026-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_documentopdf_hash_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(db_index=True, max_length=100, unique=True)),
                ('frecuencia', models.IntegerField(default=1)),
                ('temas_relacionados', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'palabras_clave',
            },
        ),
        migrations.CreateModel(
            name='MemoriaContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('resumen_contexto', models.TextField()),
                ('ultimo_tema', models.CharField(blank=True, max_length=200)),
                ('entidades_mencionadas', models.JSONField(default=list, help_text='Entidades importantes mencionadas')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'memoria_contextos',
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='memoria_con_session_496bb1_idx'), models.Index(fields=['expira_en'], name='memoria_con_expira__4bdb48_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='Identificador único del usuario (email o username)', max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado'), ('preparatoria', 'Preparatoria'), ('otro', 'Otro')], max_length=100)),
                ('intereses', models.JSONField(default=list, help_text='Carreras o temas de interés')),
                ('preferencias', models.JSONField(default=dict, help_text='Preferencias del usuario')),
                ('resumen_conversaciones', models.TextField(blank=True, help_text='Resumen comprimido de conversaciones')),
                ('total_interacciones', models.IntegerField(default=0)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'memoria_usuarios',
                'indexes': [models.Index(fields=['user_id'], name='memoria_usu_user_id_eddae0_idx'), models.Index(fields=['ultima_interaccion'], name='memoria_usu_ultima__5a02b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumenConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('resumen', models.TextField()),
                ('temas_principales', models.JSONField(default=list)),
                ('preguntas_clave', models.JSONField(default=list)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('importancia', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'resumen_conversaciones',
                'ordering': ['-importancia', '-fecha_fin'],
                'indexes': [models.Index(fields=['session_id', 'fecha_fin'], name='resumen_con_session_a65266_idx')],
            },
        ),
    ]
